### ISSUE TITLE
What are the pins for LCD_WR and LCD_RD?

### ISSUE THREAD

**Issue by jclsn** [palmerr23/ILI9486_Teensy_Library#1]
Don't know how else to contact you. I know this is not actually an issue with the code.

I am unsure where to connect RD, WR and also the SPI connectors. I guess:

- SD_SCK : Pin 13
- SD_DO   : Pin 12
- SD_DI     : Pin 11
- SD_SS    : Pin 10

No idea for RD and WR. I am only getting a white screen, no matter where I connect them.

**Comment by palmerr23** [comment]
Hi,

Yes, those are the standard SPI pins on most Arduino compatibles, including Teensy.

You will need to pull up the RESET pin.

You will need to assign the C/D pin, as it is used to differentiate between Control and Data transfers.

Personally, I wouldn't connect the MISO (DO) pin, if you are going to share the SPI with any other device. The ILI9486/8 does not  de-assert this pin when SS is OFF. Having no DI isn't a problem with a display as there is no need to read back anything from the chip once things are debugged.

**Best to ask your questions in the Teensy forum [https://forum.pjrc.com/] just search by the controller chip There's a lot of information there and a tribe of people who are very helpful.**

Hope your project goes well.
